---
# tasks file for docker
- name: Checking if docker is already installed
  ansible.builtin.shell: docker --version
  ignore_errors: true
  register: docker_check

- name: Check if we are part of a swarm
  ansible.builtin.shell: "docker info | grep -c 'Swarm: active' || /bin/true"
  register: docker_swarm_present
  when: docker_check.failed == False

- name: Install docker if OS is debian or redhat based
  block:
  - name: Fail if OS is not debian or redhat based
    ansible.builtin.fail:
      msg: "This is not a Debian or RedHat based OS, please install Docker manually"
    when: ansible_facts['os_family'] != "Debian" and ansible_facts['os_family'] != "RedHat"

  - name: Install required system packages for docker if OS is Debian based
    ansible.builtin.apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-venv', 'python3-setuptools', 'wget' ]
    when: ansible_facts['os_family'] == "Debian"

  - name: Install required system packages for docker if OS is RedHat based
    ansible.builtin.yum: name={{ item }} state=latest
    loop: [ 'ca-certificates', 'curl', 'python3-pip', 'python3-setuptools', 'wget' ]
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install python docker libraries
    ansible.builtin.command: pip3 install docker docker-compose

  - name: Add docker repo to yum
    ansible.builtin.shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install docker.io if OS is Debian
    ansible.builtin.apt: name=docker.io state=latest update_cache=yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install docker engine if OS is RedHat
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
    loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin' ]
    when: ansible_facts['os_family'] == "RedHat"

  - name: Stop docker service
    service: name=docker state=stopped
    when: usernamespaces is defined

  - name: Copy default docker daemon configuration
    ansible.builtin.template:
      src: files/docker-daemon.json
      dest: "/etc/docker/daemon.json"
      mode: 0644
    when: usernamespaces is defined

  - name: Creating docker compose location
    ansible.builtin.file:
      path: "{{ workdir }}"
      state: directory

  - name: Start docker daemon
    ansible.builtin.service: name=docker state=started enabled=true
    when: usernamespaces is defined

  - name: Gather facts so we can also access docker0
    ansible.builtin.setup:
  
  when: docker_check.failed

- name: Enable swarm on single host if swarm_mode is set and single_host == true
  block:
    
    - name: Initialize docker swarm with advertise address
      ansible.builtin.shell: docker swarm init --advertise-addr {{ advertise_address }} --listen-addr 0.0.0.0
      when: advertise_address is defined

    - name: Initialize docker swarm init without advertise address
      ansible.builtin.shell: docker swarm init --advertise-addr 127.0.0.1 --listen-addr 0.0.0.0
      when: advertise_address is not defined

    - name: Save the advertise address if advertise_address was not set
      ansible.builtin.shell: docker info | awk '/Node Address/{print $3}'
      register: advertise_address
      when: advertise_address is not defined

  when: swarm_mode == true and single_host == true and docker_swarm_present.stdout != "1"

- name: Enable swarm on multi hosts if swarm_mode is set and single_host == false
  block:

    - name: Initialize docker swarm with advertise address on first node
      ansible.builtin.shell: docker swarm init --advertise-addr {{ advertise_address }} --listen-addr 0.0.0.0
      when: advertise_address is defined and inventory_hostname == primary_manager

    - name: Initialize docker swarm init without advertise address
      ansible.builtin.shell: docker swarm init
      when: advertise_address is not defined and inventory_hostname == primary_manager

    - name: Get the manager join token so we can let other hosts join
      ansible.builtin.shell: docker swarm join-token -q manager
      register: manager_join_token
      when: inventory_hostname == primary_manager

    - name: Save the advertise address if advertise_address was not set
      ansible.builtin.shell: docker info | awk '/Node Address/{print $3}'
      register: advertise_address
      when: advertise_address is not defined and inventory_hostname == primary_manager

    - name: Save the join token and advertise_address vars
      ansible.builtin.set_fact:
        advertise_address: "{{ advertise_address }}"
        manager_join_token: "{{ manager_join_token.stdout }}"
      when: advertise_address is defined and inventory_hostname == primary_manager

    - name: Save the join token and advertise_address vars (with auto address)
      ansible.builtin.set_fact:
        advertise_address: advertise_address.stdout
        manager_join_token: manager_join_token.stdout
      when: advertise_address is not defined and inventory_hostname == primary_manager

    - name: Join other hosts to the swarm, we add them as managers as well (using advertise_address)
      ansible.builtin.shell: docker swarm join --token {{ hostvars[primary_manager]['manager_join_token'] }} {{ hostvars[primary_manager]['advertise_address'] }}
      when: inventory_hostname != primary_manager

  when: swarm_mode == true and single_host == false and docker_swarm_present.stdout != "1"

- name: Stop docker service
  service: name=docker state=stopped
  when: docker_check.failed == True

- name: Start docker daemon
  ansible.builtin.service: name=docker state=started enabled=true
  when: docker_check.failed == True