---
# tasks file for jellyfin
- name: Create folders
  shell: mkdir -p {{ workdir }}/{{ service }}/config

- name: Copy {{ service }} docker-compose jinja template
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ workdir }}/{{ service }}/docker-compose.yml"
    mode: 0644

- name: Deploy {{ service }} if swarm mode is enabled
  block:
      
    - name: Deploy {{ service }}
      shell: docker stack deploy -c {{ workdir }}/{{ service }}/docker-compose.yml {{ service }}

    - name: Wait until {{ service }} is running
      shell: docker stack services --filter name={{ service }}_{{ service }} {{ service }} | grep -c 1/1 || /bin/true
      register: service_running
      until: service_running.stdout == "1"
      retries: 40
      delay: 20

  when: swarm == true

- name: Deploy {{ service }}
  block:

    - name: Deploy {{ service }}
      shell: docker-compose -f {{ workdir }}/{{ service }}/docker-compose.yml up -d

    - name: Wait until {{ service }} is running
      shell: docker inspect {{ service }}_{{service }}_1 | jq '.[] | .State.Status'
      register: service_running
      until: service_running.stdout == '"running"'
      retries: 40
      delay: 20

  when: swarm == false