---
- name: Install docker, deploy traefik and then other services
  hosts: localhost
  gather_facts: true
  become: true

  pre_tasks:

    - name: Include vars file
      ansible.builtin.include_vars: env.yml

  roles:
    - role: docker-install
    - role: traefik
      when: traefik == true
    - role: sabnzbd
      when: sabnzbd == true
    - role: sonarr
      when: sonarr == true
    - role: radarr
      when: radarr == true
    - role: bazarr
      when: bazarr == true
    - role: readarr
      vars:
        service: "ebooks"
      when: readarr == true
    - role: readarr
      vars:
        service: "audiobooks"
      when: readarr == true
    - role: homeassistant
      when: homeassistant == true and swarm == false
    - role: emby
      when: emby == true
    - role: jellyfin
      when: jellyfin == true
    - role: wg-easy
      when: wireguard == true
    - role: slskd
      when: slskd == true
    - role: fireflyiii
      when: fireflyiii == true
    - role: whisper
      when: whisper == true
    - role: piper
      when: piper == true
    - role: sqlite-backup
      when: sqlite_backup == true
    - role: gitea
      when: gitea == true
