---
# service defaults
workdir: "/docker"
timezone: "UTC"
loadbalancer: false
swarm: false

service: "wiki"
service_version: "2"
service_port: "3000"

postgres_version: "15"
postgres_user: "wiki"
postgres_password: "wiki"
